### ISSUE TITLE
Make index.js more efficient

### ISSUE THREAD

**Issue by sserperior** [jeffreyl45/DrumKit-Keyboard#3]
In index,js, the following logic could be improved:

var numberOfDrumButtons = document.querySelectorAll(".drum").length;
for (var i = 0; i <  numberOfDrumButtons; i ++) {
    document.querySelectorAll(".drum")[i].addEventListener("click", function() {
        var buttonInnerHTML = this.innerHTML;

        makeSound(buttonInnerHTML);
        buttonAnimation(buttonInnerHTML);

    });

}

The first line selects an array of elements with the drum class and gets the length. It then iterates through this array but it queries everything again. Why does it need to do that when the elements were already obtained?

**Comment by jeffreyl45** [comment]
Fixed issue with index.js
